[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = 'specimen'
authors = [
  { name="Carolin Brune"},
]
description = "SPECIMEN: A package for strain-specific metabolic modelling."
readme = "README.md"
version = "1.0.0"
requires-python = ">=3.10"
license = {text = "GPL-3.0"}
keywords = ['Systems Biology', 'GEM', 'Metabolic Modelling', 'Python Package', 'Pipeline']

classifiers = [
    'Operating System :: MacOS',
    "Operating System :: Unix", # @TODO make it OS independant  - testing remains
    # 'Operating System :: OS Independent'
    'Programming Language :: Python',
    # Topic :: Software Development :: Libraries :: Python Modules
    'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)'
]

dependencies = [
    'biopython',
    'bofdat', # but does not work like this!!!
    'click',
    'cobra',
    'matplotlib',
    #'MCC@git+https://github.com/Biomathsys/MassChargeCuration', # @TODO test if it works
    'memote',
    'numpy',
    'pandas',
    'python-libsbml',
    'pyyaml',
    # 'refinegems >= 2.0',
    'requests',
    'SBOannotator',
    'seaborn',
    'tqdm',
    'z3-solver'
]
# additional missing tools:
#    EntrezDirect
#    DIAMOND

# @TODO:
[project.urls]
homepage = 'https://github.com/draeger-lab/SPECIMEN'
# documentation = 

[project.scripts]
specimen = "specimen.cmd_access:cli"

# include data
[tool.setuptools.packages.find]
where = ['src']
[tool.setuptools.package-data]
"specimen.data.config" = ['*.yaml']
